import Foundation

public enum AgentPolicyLevel: String, Codable, CaseIterable, Identifiable, Sendable {
    case locked
    case review
    case build
    case network
    case autonomous
    case custom

    public var id: String { rawValue }

    public static var primaryCases: [AgentPolicyLevel] {
        [.review, .autonomous, .custom]
    }

    public static var customPresetCases: [AgentPolicyLevel] {
        [.locked, .build, .network]
    }

    public var isPrimaryUserFacing: Bool {
        Self.primaryCases.contains(self)
    }

    public var userFacingLevel: AgentPolicyLevel {
        switch self {
        case .locked, .build, .network:
            .custom
        case .review, .autonomous, .custom:
            self
        }
    }

    public var displayName: String {
        switch self {
        case .locked: "Read-only preset"
        case .review: "Ask"
        case .build: "Build preset"
        case .network: "Network-heavy preset"
        case .autonomous: "Auto"
        case .custom: "Custom"
        }
    }

    public var shortDescription: String {
        switch self {
        case .locked:
            "Legacy custom preset: read and plan only."
        case .review:
            "Ask before edits, shell commands, network access, credentials, and sensitive actions."
        case .build:
            "Legacy custom preset: edit scoped files and run approved build or test commands."
        case .network:
            "Legacy custom preset: allow approved connectors and network destinations."
        case .autonomous:
            "Do routine work automatically while ASTRA still stops terminal denials, budgets, and non-negotiable safety checks."
        case .custom:
            "Use a saved configuration for exact tool, shell, network, and provider rules."
        }
    }

    public var symbolName: String {
        switch self {
        case .locked: "lock.fill"
        case .review: "lock.shield.fill"
        case .build: "hammer.fill"
        case .network: "network"
        case .autonomous: "exclamationmark.shield.fill"
        case .custom: "slider.horizontal.3"
        }
    }

    public var isBroadPermissionMode: Bool {
        self == .autonomous
    }

    public static func normalized(_ rawValue: String?) -> AgentPolicyLevel {
        guard let rawValue else {
            return .review
        }
        let normalized = rawValue
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .lowercased()
            .replacingOccurrences(of: "-", with: "_")
            .replacingOccurrences(of: " ", with: "_")
        switch normalized {
        case "ask", "ask_approval", "askapproval", "approval":
            return .review
        case "auto", "automatic":
            return .autonomous
        case "read_only", "readonly":
            return .locked
        case "network_heavy", "networkheavy":
            return .network
        default:
            return AgentPolicyLevel(rawValue: normalized) ?? .review
        }
    }
}

public enum AgentPolicyScope: String, Codable, Sendable, CaseIterable {
    case builtInDefault = "built_in_default"
    case globalDefault = "global_default"
    case workspaceDefault = "workspace_default"
    case taskOverride = "task_override"
    case taskApproval = "task_approval"
    case oneRunEscalation = "one_run_escalation"

    public var displayName: String {
        switch self {
        case .builtInDefault: "Built-in default"
        case .globalDefault: "Global default"
        case .workspaceDefault: "Workspace default"
        case .taskOverride: "Task override"
        case .taskApproval: "Task approval"
        case .oneRunEscalation: "One-run escalation"
        }
    }
}

public enum PolicyConfigOwnership: String, Codable, Sendable, CaseIterable {
    case generated
    case userOverride = "user_override"
    case externalManaged = "external_managed"
    case mixed

    public var displayName: String {
        switch self {
        case .generated: "Generated by ASTRA"
        case .userOverride: "User override"
        case .externalManaged: "Managed externally"
        case .mixed: "Mixed"
        }
    }
}

public enum PolicyDiagnosticSeverity: String, Codable, Sendable, Comparable, CaseIterable {
    case info
    case warning
    case blocked

    public static func < (lhs: PolicyDiagnosticSeverity, rhs: PolicyDiagnosticSeverity) -> Bool {
        let order: [PolicyDiagnosticSeverity] = [.info, .warning, .blocked]
        return order.firstIndex(of: lhs)! < order.firstIndex(of: rhs)!
    }
}

public struct PolicyDiagnostic: Codable, Equatable, Sendable, Identifiable {
    public var id: String
    public var severity: PolicyDiagnosticSeverity
    public var title: String
    public var message: String
    public var affectedCapability: String?
    public var remediation: String?

    public init(
        id: String,
        severity: PolicyDiagnosticSeverity,
        title: String,
        message: String,
        affectedCapability: String? = nil,
        remediation: String? = nil
    ) {
        self.id = id
        self.severity = severity
        self.title = title
        self.message = message
        self.affectedCapability = affectedCapability
        self.remediation = remediation
    }
}

public enum PolicyEnforcementTier: String, Codable, Sendable, CaseIterable {
    case providerNative = "provider_native"
    case astraBrokered = "astra_brokered"
    case osSandboxed = "os_sandboxed"
    case mixed

    public var displayName: String {
        switch self {
        case .providerNative: "Provider Native"
        case .astraBrokered: "ASTRA Brokered"
        case .osSandboxed: "OS Sandboxed"
        case .mixed: "Mixed"
        }
    }
}

public struct AgentPolicy: Codable, Equatable, Sendable {
    public var level: AgentPolicyLevel
    public var allowedTools: [String]
    public var askFirstTools: [String]
    public var deniedTools: [String]
    public var allowedShellPatterns: [String]
    public var askFirstShellPatterns: [String]
    public var deniedShellPatterns: [String]
    public var allowedURLPatterns: [String]
    public var deniedURLPatterns: [String]
    public var credentialLabels: [String]

    public init(
        level: AgentPolicyLevel,
        allowedTools: [String],
        askFirstTools: [String] = [],
        deniedTools: [String] = [],
        allowedShellPatterns: [String] = [],
        askFirstShellPatterns: [String] = [],
        deniedShellPatterns: [String] = [],
        allowedURLPatterns: [String] = [],
        deniedURLPatterns: [String] = [],
        credentialLabels: [String] = []
    ) {
        self.level = level
        self.allowedTools = Self.unique(allowedTools)
        self.askFirstTools = Self.unique(askFirstTools)
        self.deniedTools = Self.unique(deniedTools)
        self.allowedShellPatterns = Self.unique(allowedShellPatterns)
        self.askFirstShellPatterns = Self.unique(askFirstShellPatterns)
        self.deniedShellPatterns = Self.unique(deniedShellPatterns)
        self.allowedURLPatterns = Self.unique(allowedURLPatterns)
        self.deniedURLPatterns = Self.unique(deniedURLPatterns)
        self.credentialLabels = Self.unique(credentialLabels)
    }

    public static func preset(_ level: AgentPolicyLevel) -> AgentPolicy {
        switch level {
        case .locked:
            AgentPolicy(
                level: .locked,
                allowedTools: ["Read", "Glob", "Grep"],
                askFirstTools: [],
                deniedTools: ["Write", "Edit", "MultiEdit", "Bash", "WebFetch", "WebSearch"],
                deniedShellPatterns: ["*"],
                deniedURLPatterns: ["*"]
            )
        case .review:
            AgentPolicy(
                level: .review,
                allowedTools: ["Read", "Glob", "Grep"],
                askFirstTools: ["Write", "Edit", "MultiEdit", "Bash", "WebFetch", "WebSearch"],
                deniedShellPatterns: [
                    "rm:*",
                    "sudo:*",
                    "chmod:*",
                    "chown:*",
                    "git push:*",
                    "deploy:*",
                    "publish:*"
                ]
            )
        case .build:
            AgentPolicy(
                level: .build,
                allowedTools: ["Read", "Glob", "Grep", "Write", "Edit", "MultiEdit", "Bash"],
                askFirstTools: ["WebFetch", "WebSearch"],
                allowedShellPatterns: ["git:*", "swift:*", "./script/*", "xcodebuild:*"],
                deniedShellPatterns: ["sudo:*", "rm:*", "git push:*", "deploy:*", "publish:*"]
            )
        case .network:
            AgentPolicy(
                level: .network,
                allowedTools: ["Read", "Glob", "Grep", "Write", "Edit", "MultiEdit", "Bash", "WebFetch", "WebSearch"],
                askFirstTools: ["Bash(curl:*)"],
                allowedShellPatterns: ["git:*", "swift:*", "./script/*", "xcodebuild:*", "curl:*"],
                deniedShellPatterns: ["sudo:*", "rm:*", "git push:*", "deploy:*", "publish:*"]
            )
        case .autonomous:
            AgentPolicy(
                level: .autonomous,
                allowedTools: ["Read", "Glob", "Grep", "Write", "Edit", "MultiEdit", "Bash", "WebFetch", "WebSearch", "Agent"],
                allowedShellPatterns: ["*"],
                allowedURLPatterns: ["*"]
            )
        case .custom:
            AgentPolicy(
                level: .custom,
                allowedTools: ["Read", "Glob", "Grep"],
                askFirstTools: ["Write", "Edit", "MultiEdit", "Bash", "WebFetch", "WebSearch"]
            )
        }
    }

    public static func legacy(skipPermissions: Bool) -> AgentPolicy {
        preset(skipPermissions ? .autonomous : .review)
    }

    public func providerAllowedTools(requestedTools: [String]) -> [String] {
        let tools: [String]
        switch level {
        case .locked, .review:
            tools = allowedTools
        case .build, .network:
            tools = requestedTools + allowedTools
        case .autonomous:
            tools = requestedTools.isEmpty ? allowedTools : requestedTools + allowedTools
        case .custom:
            tools = allowedTools
        }
        return Self.unique(tools).filter { !isDeniedTool($0) }
    }

    public func applyingOneRunAllowedTools(_ approvedTools: [String]) -> AgentPolicy {
        let approved = Self.unique(approvedTools)
        guard !approved.isEmpty else { return self }
        let approvedKeys = Set(approved.map(Self.normalizedToolKey))

        var policy = self
        policy.allowedTools = Self.unique(policy.allowedTools + approved)
        policy.askFirstTools = policy.askFirstTools.filter { !approvedKeys.contains(Self.normalizedToolKey($0)) }
        policy.deniedTools = policy.deniedTools.filter { !approvedKeys.contains(Self.normalizedToolKey($0)) }
        return policy
    }

    private func isDeniedTool(_ tool: String) -> Bool {
        let key = Self.normalizedToolKey(tool)
        return deniedTools.contains { Self.normalizedToolKey($0) == key }
    }

    private static func normalizedToolKey(_ value: String) -> String {
        value.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
    }

    private static func unique(_ values: [String]) -> [String] {
        Array(Set(values.filter { !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty })).sorted()
    }
}

public struct ProviderPolicyFeatures: Codable, Equatable, Sendable {
    public var supportsAllowTools: Bool
    public var supportsDenyTools: Bool
    public var supportsAskFirstMode: Bool
    public var supportsPathScoping: Bool
    public var supportsURLAllowlist: Bool
    public var supportsURLDenylist: Bool
    public var supportsSecretEnvRedaction: Bool
    public var supportsGeneratedSettingsFile: Bool
    public var supportsPerRunFlags: Bool
    public var supportsInteractiveCallbacks: Bool
    public var supportsManagedSettings: Bool
    public var supportsMachineReadableEvents: Bool
    public var supportsBroadAllowAll: Bool

    public init(
        supportsAllowTools: Bool,
        supportsDenyTools: Bool,
        supportsAskFirstMode: Bool,
        supportsPathScoping: Bool,
        supportsURLAllowlist: Bool,
        supportsURLDenylist: Bool,
        supportsSecretEnvRedaction: Bool,
        supportsGeneratedSettingsFile: Bool,
        supportsPerRunFlags: Bool,
        supportsInteractiveCallbacks: Bool,
        supportsManagedSettings: Bool,
        supportsMachineReadableEvents: Bool,
        supportsBroadAllowAll: Bool
    ) {
        self.supportsAllowTools = supportsAllowTools
        self.supportsDenyTools = supportsDenyTools
        self.supportsAskFirstMode = supportsAskFirstMode
        self.supportsPathScoping = supportsPathScoping
        self.supportsURLAllowlist = supportsURLAllowlist
        self.supportsURLDenylist = supportsURLDenylist
        self.supportsSecretEnvRedaction = supportsSecretEnvRedaction
        self.supportsGeneratedSettingsFile = supportsGeneratedSettingsFile
        self.supportsPerRunFlags = supportsPerRunFlags
        self.supportsInteractiveCallbacks = supportsInteractiveCallbacks
        self.supportsManagedSettings = supportsManagedSettings
        self.supportsMachineReadableEvents = supportsMachineReadableEvents
        self.supportsBroadAllowAll = supportsBroadAllowAll
    }
}

public struct PolicyRenderContext: Codable, Equatable, Sendable {
    public var runtimeID: AgentRuntimeID
    public var model: String
    public var workspacePath: String
    public var additionalPaths: [String]
    public var requestedAllowedTools: [String]
    public var localToolCommands: [String]
    public var environmentKeyNames: [String]
    public var credentialLabels: [String]
    public var providerFeatures: ProviderPolicyFeatures
    public var providerConfigOwnership: PolicyConfigOwnership
    public var existingProviderConfigSummary: String?

    public init(
        runtimeID: AgentRuntimeID,
        model: String,
        workspacePath: String,
        additionalPaths: [String],
        requestedAllowedTools: [String],
        localToolCommands: [String],
        environmentKeyNames: [String],
        credentialLabels: [String],
        providerFeatures: ProviderPolicyFeatures,
        providerConfigOwnership: PolicyConfigOwnership = .generated,
        existingProviderConfigSummary: String? = nil
    ) {
        self.runtimeID = runtimeID
        self.model = model
        self.workspacePath = workspacePath
        self.additionalPaths = Array(Set(additionalPaths)).sorted()
        self.requestedAllowedTools = Array(Set(requestedAllowedTools)).sorted()
        self.localToolCommands = Array(Set(localToolCommands)).sorted()
        self.environmentKeyNames = Array(Set(environmentKeyNames)).sorted()
        self.credentialLabels = Array(Set(credentialLabels)).sorted()
        self.providerFeatures = providerFeatures
        self.providerConfigOwnership = providerConfigOwnership
        self.existingProviderConfigSummary = existingProviderConfigSummary
    }
}

public struct ProviderRuntimeSupportToolDescriptor: Codable, Equatable, Sendable, Identifiable {
    public var id: String { name }
    public var name: String
    public var providerNativePermission: String?
    public var purpose: String
    public var allowedInputKeys: [String]
    public var deniedInputKeys: [String]
    public var maxSummaryLength: Int

    private enum CodingKeys: String, CodingKey {
        case name
        case providerNativePermission
        case purpose
        case allowedInputKeys
        case deniedInputKeys
        case maxSummaryLength
    }

    public init(
        name: String,
        providerNativePermission: String? = nil,
        purpose: String,
        allowedInputKeys: [String] = [],
        deniedInputKeys: [String] = Self.defaultDeniedActionInputKeys,
        maxSummaryLength: Int = 500
    ) {
        self.name = name.trimmingCharacters(in: .whitespacesAndNewlines)
        let nativePermission = providerNativePermission?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        self.providerNativePermission = nativePermission.isEmpty ? nil : nativePermission
        self.purpose = purpose.trimmingCharacters(in: .whitespacesAndNewlines)
        self.allowedInputKeys = Array(Set(allowedInputKeys.map {
            $0.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        }.filter { !$0.isEmpty })).sorted()
        self.deniedInputKeys = Array(Set(deniedInputKeys.map {
            $0.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        }.filter { !$0.isEmpty })).sorted()
        self.maxSummaryLength = max(0, maxSummaryLength)
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.init(
            name: try container.decode(String.self, forKey: .name),
            providerNativePermission: try container.decodeIfPresent(String.self, forKey: .providerNativePermission),
            purpose: try container.decode(String.self, forKey: .purpose),
            allowedInputKeys: try container.decodeIfPresent([String].self, forKey: .allowedInputKeys) ?? [],
            deniedInputKeys: try container.decodeIfPresent([String].self, forKey: .deniedInputKeys) ?? Self.defaultDeniedActionInputKeys,
            maxSummaryLength: try container.decodeIfPresent(Int.self, forKey: .maxSummaryLength) ?? 500
        )
    }

    public static let defaultDeniedActionInputKeys: [String] = [
        "body",
        "cmd",
        "command",
        "cwd",
        "directory",
        "endpoint",
        "file",
        "file_path",
        "filepath",
        "href",
        "method",
        "path",
        "request",
        "script",
        "shell",
        "target",
        "target_path",
        "uri",
        "url"
    ]
}

public struct ProviderPolicyRender: Codable, Equatable, Sendable {
    public var providerID: AgentRuntimeID
    public var adapterVersion: Int
    public var policyLevel: AgentPolicyLevel
    public var configOwnership: PolicyConfigOwnership
    public var permissionMode: String
    public var allowedTools: [String]
    public var runtimeSupportTools: [ProviderRuntimeSupportToolDescriptor]
    public var askFirstTools: [String]
    public var deniedTools: [String]
    public var allowedShellPatterns: [String]
    public var askFirstShellPatterns: [String]
    public var deniedShellPatterns: [String]
    public var allowedURLPatterns: [String]
    public var deniedURLPatterns: [String]
    public var cliArgumentsSummary: [String]
    public var settingsSummary: String
    public var generatedConfigPreview: String
    public var enforcementTiers: [PolicyEnforcementTier]
    public var diagnostics: [PolicyDiagnostic]
    public var usesBroadProviderPermissions: Bool

    private enum CodingKeys: String, CodingKey {
        case providerID
        case adapterVersion
        case policyLevel
        case configOwnership
        case permissionMode
        case allowedTools
        case runtimeSupportTools
        case askFirstTools
        case deniedTools
        case allowedShellPatterns
        case askFirstShellPatterns
        case deniedShellPatterns
        case allowedURLPatterns
        case deniedURLPatterns
        case cliArgumentsSummary
        case settingsSummary
        case generatedConfigPreview
        case enforcementTiers
        case diagnostics
        case usesBroadProviderPermissions
    }

    public init(
        providerID: AgentRuntimeID,
        adapterVersion: Int,
        policyLevel: AgentPolicyLevel,
        configOwnership: PolicyConfigOwnership,
        permissionMode: String,
        allowedTools: [String],
        runtimeSupportTools: [ProviderRuntimeSupportToolDescriptor] = [],
        askFirstTools: [String] = [],
        deniedTools: [String],
        allowedShellPatterns: [String],
        askFirstShellPatterns: [String] = [],
        deniedShellPatterns: [String],
        allowedURLPatterns: [String],
        deniedURLPatterns: [String],
        cliArgumentsSummary: [String],
        settingsSummary: String,
        generatedConfigPreview: String,
        enforcementTiers: [PolicyEnforcementTier],
        diagnostics: [PolicyDiagnostic],
        usesBroadProviderPermissions: Bool
    ) {
        self.providerID = providerID
        self.adapterVersion = adapterVersion
        self.policyLevel = policyLevel
        self.configOwnership = configOwnership
        self.permissionMode = permissionMode
        self.allowedTools = allowedTools
        self.runtimeSupportTools = runtimeSupportTools.sorted { $0.name < $1.name }
        self.askFirstTools = askFirstTools
        self.deniedTools = deniedTools
        self.allowedShellPatterns = allowedShellPatterns
        self.askFirstShellPatterns = askFirstShellPatterns
        self.deniedShellPatterns = deniedShellPatterns
        self.allowedURLPatterns = allowedURLPatterns
        self.deniedURLPatterns = deniedURLPatterns
        self.cliArgumentsSummary = cliArgumentsSummary
        self.settingsSummary = settingsSummary
        self.generatedConfigPreview = generatedConfigPreview
        self.enforcementTiers = enforcementTiers
        self.diagnostics = diagnostics
        self.usesBroadProviderPermissions = usesBroadProviderPermissions
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        providerID = try container.decode(AgentRuntimeID.self, forKey: .providerID)
        adapterVersion = try container.decode(Int.self, forKey: .adapterVersion)
        policyLevel = try container.decode(AgentPolicyLevel.self, forKey: .policyLevel)
        configOwnership = try container.decode(PolicyConfigOwnership.self, forKey: .configOwnership)
        permissionMode = try container.decode(String.self, forKey: .permissionMode)
        allowedTools = try container.decode([String].self, forKey: .allowedTools)
        runtimeSupportTools = try container.decodeIfPresent([ProviderRuntimeSupportToolDescriptor].self, forKey: .runtimeSupportTools) ?? []
        askFirstTools = try container.decodeIfPresent([String].self, forKey: .askFirstTools) ?? []
        deniedTools = try container.decode([String].self, forKey: .deniedTools)
        allowedShellPatterns = try container.decode([String].self, forKey: .allowedShellPatterns)
        askFirstShellPatterns = try container.decodeIfPresent([String].self, forKey: .askFirstShellPatterns) ?? []
        deniedShellPatterns = try container.decode([String].self, forKey: .deniedShellPatterns)
        allowedURLPatterns = try container.decode([String].self, forKey: .allowedURLPatterns)
        deniedURLPatterns = try container.decode([String].self, forKey: .deniedURLPatterns)
        cliArgumentsSummary = try container.decode([String].self, forKey: .cliArgumentsSummary)
        settingsSummary = try container.decode(String.self, forKey: .settingsSummary)
        generatedConfigPreview = try container.decodeIfPresent(String.self, forKey: .generatedConfigPreview) ?? ""
        enforcementTiers = try container.decode([PolicyEnforcementTier].self, forKey: .enforcementTiers)
        diagnostics = try container.decode([PolicyDiagnostic].self, forKey: .diagnostics)
        usesBroadProviderPermissions = try container.decode(Bool.self, forKey: .usesBroadProviderPermissions)
    }
}

public enum PolicyObservedEventKind: String, Codable, Sendable, CaseIterable {
    case toolUse = "tool_use"
    case toolResult = "tool_result"
    case deniedAction = "denied_action"
    case fileChange = "file_change"
    case networkAccess = "network_access"
}

public struct PolicyObservedEvent: Codable, Equatable, Sendable, Identifiable {
    public var id: UUID
    public var kind: PolicyObservedEventKind
    public var toolName: String?
    public var command: String?
    public var path: String?
    public var url: String?
    public var summary: String?
    public var inputKeys: [String]

    private enum CodingKeys: String, CodingKey {
        case id
        case kind
        case toolName
        case command
        case path
        case url
        case summary
        case inputKeys
    }

    public init(
        id: UUID = UUID(),
        kind: PolicyObservedEventKind,
        toolName: String? = nil,
        command: String? = nil,
        path: String? = nil,
        url: String? = nil,
        summary: String? = nil,
        inputKeys: [String] = []
    ) {
        self.id = id
        self.kind = kind
        self.toolName = toolName
        self.command = command
        self.path = path
        self.url = url
        self.summary = summary
        self.inputKeys = Self.normalizedInputKeys(inputKeys)
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decodeIfPresent(UUID.self, forKey: .id) ?? UUID()
        kind = try container.decode(PolicyObservedEventKind.self, forKey: .kind)
        toolName = try container.decodeIfPresent(String.self, forKey: .toolName)
        command = try container.decodeIfPresent(String.self, forKey: .command)
        path = try container.decodeIfPresent(String.self, forKey: .path)
        url = try container.decodeIfPresent(String.self, forKey: .url)
        summary = try container.decodeIfPresent(String.self, forKey: .summary)
        inputKeys = Self.normalizedInputKeys(try container.decodeIfPresent([String].self, forKey: .inputKeys) ?? [])
    }

    public init?(providerEvent: ParsedEvent) {
        switch providerEvent {
        case .toolUse(let name, _, let input):
            let normalizedInput = Self.normalizedToolInput(input)
            let inputKeys = Self.providerInputKeys(from: input)
            let patchText = Self.isPatchTool(name)
                ? Self.firstString(in: normalizedInput, keys: ["arguments", "input", "args", "summary"])
                : nil
            let patchPath = patchText.flatMap { Self.patchFilePaths(in: $0).first }
            let command = Self.firstString(in: normalizedInput, keys: ["command", "cmd"])
                ?? (Self.isShellTool(name) ? Self.firstString(in: normalizedInput, keys: ["summary"]) : nil)
            let path = Self.firstString(in: normalizedInput, keys: ["file_path", "filePath", "path", "target_path", "targetPath"])
                ?? patchPath
                ?? (Self.isFileTool(name) && !Self.isPatchTool(name) ? Self.firstString(in: normalizedInput, keys: ["summary"]) : nil)
            let url = Self.firstString(in: input, keys: ["url", "uri"])
                ?? Self.firstString(in: normalizedInput, keys: ["url", "uri"])
                ?? (Self.isNetworkTool(name) ? Self.firstString(in: normalizedInput, keys: ["summary"]) : nil)
                ?? command.flatMap(Self.firstURL(in:))
            let kind: PolicyObservedEventKind = if path != nil && Self.isMutationTool(name) {
                .fileChange
            } else if url != nil || Self.isNetworkTool(name) {
                .networkAccess
            } else {
                .toolUse
            }
            self.init(
                kind: kind,
                toolName: name,
                command: command,
                path: path,
                url: url,
                summary: command ?? patchText ?? path ?? url ?? Self.firstString(in: normalizedInput, keys: ["summary"]),
                inputKeys: inputKeys
            )
        case .toolResult(let toolId, let content):
            self.init(kind: .toolResult, toolName: toolId.isEmpty ? nil : toolId, summary: String(content.prefix(500)))
        case .permissionDenied(let tool, let reason):
            self.init(kind: .deniedAction, toolName: tool, summary: String(reason.prefix(500)))
        default:
            return nil
        }
    }

    private static func providerInputKeys(from input: [String: Any]?) -> [String] {
        guard let input else { return [] }
        if let summary = input["summary"] as? String,
           let summaryObject = jsonDictionary(from: summary) {
            let nonSummaryKeys = input.keys.filter { $0 != "summary" }
            if nonSummaryKeys.isEmpty {
                return normalizedInputKeys(Array(summaryObject.keys))
            }
        }
        return normalizedInputKeys(Array(input.keys))
    }

    private static func normalizedInputKeys(_ keys: [String]) -> [String] {
        Array(Set(keys.map {
            $0.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        }.filter { !$0.isEmpty })).sorted()
    }

    private static func normalizedToolInput(_ input: [String: Any]?) -> [String: Any]? {
        guard let input else { return nil }
        var normalized = input
        mergeToolArgumentContainers(from: input, into: &normalized)
        if let summary = input["summary"] as? String,
           let summaryObject = jsonDictionary(from: summary) {
            mergeToolArgumentContainers(from: summaryObject, into: &normalized)
            mergeMissingValues(from: summaryObject, into: &normalized)
        }
        return normalized
    }

    private static func mergeToolArgumentContainers(from source: [String: Any], into destination: inout [String: Any]) {
        for key in ["input", "arguments", "args"] {
            if let nested = source[key] as? [String: Any] {
                mergeMissingValues(from: nested, into: &destination)
            } else if let nestedText = source[key] as? String,
                      let nested = jsonDictionary(from: nestedText) {
                mergeMissingValues(from: nested, into: &destination)
            }
        }
    }

    private static func mergeMissingValues(from source: [String: Any], into destination: inout [String: Any]) {
        for (key, value) in source where destination[key] == nil {
            destination[key] = value
        }
    }

    private static func firstString(in input: [String: Any]?, keys: [String]) -> String? {
        guard let input else { return nil }
        for key in keys {
            if let value = input[key] as? String {
                let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
                if !trimmed.isEmpty { return trimmed }
            }
        }
        return nil
    }

    private static func isShellTool(_ tool: String) -> Bool {
        ["bash", "shell"].contains(tool.trimmingCharacters(in: .whitespacesAndNewlines).lowercased())
    }

    private static func isFileTool(_ tool: String) -> Bool {
        ["read", "view", "write", "create", "edit", "multiedit", "multi_edit", "apply_patch"].contains(
            tool.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        )
    }

    private static func isMutationTool(_ tool: String) -> Bool {
        ["write", "create", "edit", "multiedit", "multi_edit", "apply_patch"].contains(tool.trimmingCharacters(in: .whitespacesAndNewlines).lowercased())
    }

    private static func isNetworkTool(_ tool: String) -> Bool {
        ["webfetch", "websearch"].contains(tool.trimmingCharacters(in: .whitespacesAndNewlines).lowercased())
    }

    private static func isPatchTool(_ tool: String) -> Bool {
        tool.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() == "apply_patch"
    }

    public static func patchFilePaths(in patch: String) -> [String] {
        let patterns = [
            #"(?m)^\*\*\* (?:Add|Update|Delete) File:\s*(.+?)\s*$"#,
            #"(?m)^\*\*\* Move to:\s*(.+?)\s*$"#
        ]
        var paths: [String] = []
        for pattern in patterns {
            guard let regex = try? NSRegularExpression(pattern: pattern) else { continue }
            let range = NSRange(patch.startIndex..<patch.endIndex, in: patch)
            for match in regex.matches(in: patch, range: range) {
                guard match.numberOfRanges > 1,
                      let valueRange = Range(match.range(at: 1), in: patch) else {
                    continue
                }
                let path = String(patch[valueRange]).trimmingCharacters(in: .whitespacesAndNewlines)
                if !path.isEmpty {
                    paths.append(path)
                }
            }
        }
        var seen: Set<String> = []
        return paths.filter { seen.insert($0).inserted }
    }

    private static func jsonDictionary(from text: String) -> [String: Any]? {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.hasPrefix("{"),
              let data = trimmed.data(using: .utf8),
              let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            return nil
        }
        return object
    }

    private static func firstURL(in text: String) -> String? {
        guard let regex = try? NSRegularExpression(pattern: #"https?://[^\s"')<>]+"#) else { return nil }
        let range = NSRange(text.startIndex..<text.endIndex, in: text)
        guard let match = regex.firstMatch(in: text, range: range),
              let valueRange = Range(match.range, in: text) else {
            return nil
        }
        return String(text[valueRange])
    }
}

public enum PermissionRequest: Codable, Equatable, Sendable {
    case tool(name: String, context: String?)
    case shell(command: String, toolName: String?)
    case fileWrite(path: String, toolName: String?)
    case network(url: String, toolName: String?)
    case credential(label: String)
    case providerNativePrompt(toolName: String, context: String?)
}

public enum PermissionGrant: Codable, Equatable, Sendable, Hashable {
    case tool(name: String)
    case shellCommand(executable: String, pattern: String)
    case filePath(path: String, access: String)
    case networkPattern(pattern: String)
    case providerTool(name: String)

    public var displayName: String {
        switch self {
        case .tool(let name):
            name
        case .shellCommand(let executable, let pattern):
            "shell(\(executable):\(pattern))"
        case .filePath(let path, let access):
            "\(access):\(path)"
        case .networkPattern(let pattern):
            "network(\(pattern))"
        case .providerTool(let name):
            name
        }
    }
}

public enum PermissionDecision: Codable, Equatable, Sendable {
    case allow
    case askUser(message: String, grants: [PermissionGrant])
    case deny(reason: String, stopReason: String)
    case terminalProviderDenial(reason: String, stopReason: String)

    public var grants: [PermissionGrant] {
        switch self {
        case .askUser(_, let grants):
            grants
        case .allow, .deny, .terminalProviderDenial:
            []
        }
    }
}

public struct PermissionApprovalEventPayload: Codable, Equatable, Sendable {
    public var brokerVersion: Int
    public var providerID: AgentRuntimeID
    public var request: PermissionRequest
    public var decision: PermissionDecision
    public var grants: [PermissionGrant]
    public var displayMessage: String
    /// Correlation id for a live in-flight ask. Lets the open-request UI pair
    /// this request with its `permission.request.resolved` event even when
    /// several asks are pending concurrently. Nil for the legacy
    /// pause-and-relaunch path (closed by `task.approved`).
    public var requestID: String?

    public init(
        brokerVersion: Int,
        providerID: AgentRuntimeID,
        request: PermissionRequest,
        decision: PermissionDecision,
        grants: [PermissionGrant],
        displayMessage: String,
        requestID: String? = nil
    ) {
        self.brokerVersion = brokerVersion
        self.providerID = providerID
        self.request = request
        self.decision = decision
        self.grants = grants
        self.displayMessage = displayMessage
        self.requestID = requestID
    }

    public static func decoded(from payload: String) -> PermissionApprovalEventPayload? {
        guard let data = payload.data(using: .utf8) else { return nil }
        return try? JSONDecoder().decode(PermissionApprovalEventPayload.self, from: data)
    }

    public func encodedString() -> String? {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.withoutEscapingSlashes]
        guard let data = try? encoder.encode(self) else { return nil }
        return String(data: data, encoding: .utf8)
    }
}

public struct RunPermissionManifest: Codable, Equatable, Sendable, Identifiable {
    public struct MCPServer: Codable, Equatable, Sendable, Identifiable {
        public var id: String
        public var packageID: String
        public var displayName: String
        public var transport: String
        public var allowedTools: [String]
        public var excludedTools: [String]
        public var resourcesEnabled: Bool
        public var promptsEnabled: Bool
        public var trustLevel: String

        public init(
            id: String,
            packageID: String,
            displayName: String,
            transport: String,
            allowedTools: [String] = [],
            excludedTools: [String] = [],
            resourcesEnabled: Bool = false,
            promptsEnabled: Bool = false,
            trustLevel: String
        ) {
            self.id = id
            self.packageID = packageID
            self.displayName = displayName
            self.transport = transport
            self.allowedTools = allowedTools
            self.excludedTools = excludedTools
            self.resourcesEnabled = resourcesEnabled
            self.promptsEnabled = promptsEnabled
            self.trustLevel = trustLevel
        }
    }

    public var id: UUID
    public var createdAt: Date
    public var taskID: UUID
    public var runID: UUID
    public var phase: String
    public var providerID: AgentRuntimeID
    public var providerVersion: String?
    public var model: String
    public var policyLevel: AgentPolicyLevel
    public var policyScope: AgentPolicyScope
    public var providerRender: ProviderPolicyRender
    public var workspacePath: String
    public var additionalPaths: [String]
    public var environmentKeyNames: [String]
    public var credentialLabels: [String]
    public var mcpServers: [MCPServer]
    public var approvalsGranted: [String]
    public var approvalGrants: [PermissionGrant]
    public var observedToolUseCount: Int
    public var observedDeniedCount: Int
    public var observedFileChangeCount: Int

    enum CodingKeys: String, CodingKey {
        case id
        case createdAt
        case taskID
        case runID
        case phase
        case providerID
        case providerVersion
        case model
        case policyLevel
        case policyScope
        case providerRender
        case workspacePath
        case additionalPaths
        case environmentKeyNames
        case credentialLabels
        case mcpServers
        case approvalsGranted
        case approvalGrants
        case observedToolUseCount
        case observedDeniedCount
        case observedFileChangeCount
    }

    public init(
        id: UUID = UUID(),
        createdAt: Date = Date(),
        taskID: UUID,
        runID: UUID,
        phase: String,
        providerID: AgentRuntimeID,
        providerVersion: String?,
        model: String,
        policyLevel: AgentPolicyLevel,
        policyScope: AgentPolicyScope,
        providerRender: ProviderPolicyRender,
        workspacePath: String,
        additionalPaths: [String],
        environmentKeyNames: [String],
        credentialLabels: [String],
        mcpServers: [MCPServer] = [],
        approvalsGranted: [String],
        approvalGrants: [PermissionGrant] = [],
        observedToolUseCount: Int = 0,
        observedDeniedCount: Int = 0,
        observedFileChangeCount: Int = 0
    ) {
        self.id = id
        self.createdAt = createdAt
        self.taskID = taskID
        self.runID = runID
        self.phase = phase
        self.providerID = providerID
        self.providerVersion = providerVersion
        self.model = model
        self.policyLevel = policyLevel
        self.policyScope = policyScope
        self.providerRender = providerRender
        self.workspacePath = workspacePath
        self.additionalPaths = Array(Set(additionalPaths)).sorted()
        self.environmentKeyNames = Array(Set(environmentKeyNames)).sorted()
        self.credentialLabels = Array(Set(credentialLabels)).sorted()
        self.mcpServers = mcpServers.sorted {
            if $0.packageID != $1.packageID { return $0.packageID < $1.packageID }
            return $0.id < $1.id
        }
        self.approvalsGranted = Array(Set(approvalsGranted)).sorted()
        self.approvalGrants = Array(Set(approvalGrants)).sorted { $0.displayName < $1.displayName }
        self.observedToolUseCount = observedToolUseCount
        self.observedDeniedCount = observedDeniedCount
        self.observedFileChangeCount = observedFileChangeCount
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(UUID.self, forKey: .id)
        self.createdAt = try container.decode(Date.self, forKey: .createdAt)
        self.taskID = try container.decode(UUID.self, forKey: .taskID)
        self.runID = try container.decode(UUID.self, forKey: .runID)
        self.phase = try container.decode(String.self, forKey: .phase)
        self.providerID = try container.decode(AgentRuntimeID.self, forKey: .providerID)
        self.providerVersion = try container.decodeIfPresent(String.self, forKey: .providerVersion)
        self.model = try container.decode(String.self, forKey: .model)
        self.policyLevel = try container.decode(AgentPolicyLevel.self, forKey: .policyLevel)
        self.policyScope = try container.decode(AgentPolicyScope.self, forKey: .policyScope)
        self.providerRender = try container.decode(ProviderPolicyRender.self, forKey: .providerRender)
        self.workspacePath = try container.decode(String.self, forKey: .workspacePath)
        self.additionalPaths = try container.decode([String].self, forKey: .additionalPaths)
        self.environmentKeyNames = try container.decode([String].self, forKey: .environmentKeyNames)
        self.credentialLabels = try container.decode([String].self, forKey: .credentialLabels)
        self.mcpServers = try container.decodeIfPresent([MCPServer].self, forKey: .mcpServers) ?? []
        self.approvalsGranted = try container.decode([String].self, forKey: .approvalsGranted)
        self.approvalGrants = try container.decodeIfPresent([PermissionGrant].self, forKey: .approvalGrants) ?? []
        self.observedToolUseCount = try container.decodeIfPresent(Int.self, forKey: .observedToolUseCount) ?? 0
        self.observedDeniedCount = try container.decodeIfPresent(Int.self, forKey: .observedDeniedCount) ?? 0
        self.observedFileChangeCount = try container.decodeIfPresent(Int.self, forKey: .observedFileChangeCount) ?? 0
    }
}
